hapi:
  fhir:
    etag-support-enabled: false
    default-pretty-print: true
    default-encoding: json
    interceptor:
      open-api-enabled: true
      response-highlighter-enabled: true
      authorization-enabled: false
      fhir-path-filter-enabled: false
    logger:
      logging-enabled: true
    validation:
      requests-enabled: true
      responses-enabled: false
    server:
      path: /hapi
      address: http://localhost:${server.port}${hapi.fhir.server.path}
    profiles:
      no-basis:
        name: hl7.fhir.no.basis
        version: 2.1.1
        url: https://packages.simplifier.net/${hapi.fhir.profiles.no-basis.name}/${hapi.fhir.profiles.no-basis.version}
        #path: classpath:packages/${hapi.fhir.profiles.no-basis.name}-${hapi.fhir.profiles.no-basis.version}.tgz
logging:
  file:
    name: /log/fhir.log
server:
  port: 8080
  http2:
    enabled: true
  error:
    include-message: always
  tomcat:
    accesslog:
      directory: /log/access-logs
      enabled: false
      file-date-format: yyyy-MM-dd
      suffix: .log.json
      pattern: '{"time_local":"%t", "remote_addr" :"%a", "host" :"%h", "remote_user": "%u",
             "request-method":"%m", "status": "%s", "body_bytes_sent": "%B", "request_time": "%T",
             "http_referrer": "%{Referer}i","http_user_agent": "%{User-Agent}i", "request": "%r"},'
      prefix: access_log_
  max-http-header-size: 100KB
management:
  info:
    env:
      enabled: true
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
    heapdump:
      enabled: false
    mappings:
      enabled: false
    configprops:
      keys-to-sanitize: [ ".*password$", ".*secret$", ".*key$", ".*token$", ".*credentials.*" ]
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
info:
  profiles:
    no-basis-version: ${hapi.fhir.profiles.no-basis.version}