{{- if (.Values.ingress.server.enabled) }}
  {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1"  }}
apiVersion: networking.k8s.io/v1
  {{- else }}
apiVersion: networking.k8s.io/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{.Values.ingress.server.name}}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "fhir.server.labels" . | nindent 4 }}
  annotations:
    {{- if (.Values.ingress.class) }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "64k"
    nginx.ingress.kubernetes.io/ssl-redirect: "{{.Values.ingress.server.sslRedirect}}"
    {{- if (.Values.ingress.server.rewriteTarget) }}
    nginx.ingress.kubernetes.io/rewrite-target: {{.Values.ingress.server.rewriteTarget}}
  {{- end }}
spec:
  {{- if (.Values.ingress.tls.enabled) }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
    - secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1"  }}
          - path: /fhir/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.server.name }}
                port:
                  number: {{ .Values.service.server.port.backend }}
          {{- else }}
          - path: /fhir/
            backend:
              serviceName: {{ .Values.server.name }}
              servicePort: {{ .Values.service.server.port.backend }}
  {{- end }}
  {{- end }}