{{- if (.Values.serviceAccount.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "fhir.server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
automountServiceAccountToken: true
  {{- end }}
---
  {{- if (.Values.role.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.role.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "fhir.server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
  {{- end }}
---
  {{- if (.Values.roleBinding.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "fhir.server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.role.name }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}