name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --no-transfer-progress

      - name: Build Docker image
        if: github.event_name == 'push'
        run: |
          docker build \
          --build-arg JAR_FILE=./target/hapi-fhir-server.jar \
          -f ./Dockerfile -t hapi-fhir-server:latest \
          ./hapi-fhir-server